spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafystudy@gmail.com
    password: ssafy123@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
